export { 
  useUsers, 
  useUser, 
  useAllUsersForAssignment,
  useCreateUser, 
  useUpdateUser, 
  useDeactivateUser,
  useBulkUpdateRole,
  useBulkDeactivate,
  useBulkActivate,
  useBulkDelete,
  useDeletionPreflight,
  useArchiveUser,
  useTransferOwnership,
  usePermanentDelete,
  useBulkDeletionPreflight,
  useBulkDeleteWithPreflight,
  type UseUsersOptions,
  type DeletionPreflightResponse,
  type BulkPreflightUser,
  type BulkPreflightResponse,
  type BulkDeleteResult,
} from "./hooks/use-users-api";

export {
  useUserProfile,
  useUpdateProfile,
  useUserIdentities,
  useAllUserIdentities,
  useLinkIdentity,
  useUnlinkIdentity,
  useUpdateIdentity,
  useAvailableSystems,
  useMergeUsers,
} from "./hooks/use-identity-api";
