import type { SchemaDefinition } from "./types";

export const SCHEMA_DEFINITIONS: Record<string, SchemaDefinition[]> = {
  all: [
    { sheet: "Projects", columns: ["id", "name", "description", "status", "startDate", "deadline", "progress", "frameworkId", "defaultMappingTemplateId", "permissions", "sprintDurationWeeks", "ownerId", "client", "riskLevel", "externalRefs"] },
    { sheet: "Deliverables", columns: ["id", "projectId", "title", "description", "status", "ownerId", "startDate", "dueDate", "progress", "externalRefs"] },
    { sheet: "Epics", columns: ["id", "deliverableId", "title", "description", "status", "ownerId", "startDate", "endDate", "progress", "stageIds", "externalRefs"] },
    { sheet: "ProjectStages", columns: ["id", "projectId", "name", "description", "order", "type", "status", "startDate", "endDate"] },
    { sheet: "Tasks", columns: ["id", "title", "description", "project", "projectId", "stageId", "epicId", "status", "assigneeId", "deadline", "priority", "milestoneId", "sprintId", "estimateHours", "effort", "tags", "blocked", "blockerReason", "updatedAt", "taskTypeId", "parentTaskId", "externalRefs"] },
    { sheet: "Milestones", columns: ["id", "projectId", "name", "description", "phase", "stageId", "targetDate", "status", "ownerId", "scopeType", "completionMode", "completionTargetPercent", "tags", "createdAt", "updatedAt", "progressTotalTasks", "progressCompletedTasks", "progressPercentComplete", "progressLastCalculatedAt", "progressPercent", "isBillingGate", "requiredCompletionRatio", "scopeRules", "createdBy", "updatedBy"] },
    { sheet: "MilestoneScopeRules", columns: ["id", "milestoneId", "rules", "lastEvaluatedAt"] },
    { sheet: "MilestoneTaskLinks", columns: ["id", "milestoneId", "taskId", "projectId", "source", "ruleId", "locked", "createdAt", "updatedAt"] },
    { sheet: "Sprints", columns: ["id", "projectId", "ownerUserId", "name", "goal", "startDate", "endDate", "status", "capacityHours", "notes", "autoStart", "closedAt", "createdAt", "updatedAt"] },
    { sheet: "SprintMembers", columns: ["id", "sprintId", "userId", "capacityHours", "capacityPoints"] },
    { sheet: "SprintScopeEvents", columns: ["id", "sprintId", "taskId", "userId", "eventType", "occurredAt", "note"] },
    { sheet: "SprintScopeTargets", columns: ["id", "sprintId", "targetType", "targetId", "autoSyncTasks", "createdAt"] },
    { sheet: "SprintPulseUpdates", columns: ["id", "sprintId", "userId", "date", "didText", "nextText", "blockersText", "referencedTaskIds", "createdAt", "updatedAt"] },
    { sheet: "TaskDependencies", columns: ["id", "taskId", "dependsOnTaskId", "dependencyType", "createdAt"] },
    { sheet: "TaskTypes", columns: ["id", "name", "color", "icon", "isDefault", "order", "createdAt"] },
    { sheet: "ProjectTaskTypes", columns: ["id", "projectId", "taskTypeId", "name", "color", "icon", "isEnabled", "isDefault", "order", "createdAt"] },
    { sheet: "ProjectTaskStatuses", columns: ["id", "projectId", "label", "color", "isDefault", "order", "createdAt"] },
    { sheet: "ProjectSettings", columns: ["id", "projectId", "useCustomStatuses", "useCustomTaskTypes", "updatedAt"] },
    { sheet: "Activity", columns: ["id", "user", "action", "target", "time", "details", "avatar"] },
    { sheet: "Comments", columns: ["id", "taskId", "authorId", "authorName", "body", "createdAt"] },
    { sheet: "Attachments", columns: ["id", "taskId", "fileName", "url", "fileType", "size", "uploadedAt", "uploadedBy"] },
    { sheet: "History", columns: ["id", "taskId", "field", "oldValue", "newValue", "changedAt", "changedBy"] },
    { sheet: "SavedViews", columns: ["id", "name", "description", "stageIds", "viewType", "visibility", "isDefault", "config"] },
    { sheet: "GuidanceItems", columns: ["id", "title", "body", "priority", "stageId"] },
    { sheet: "ProjectTemplates", columns: ["id", "name", "description", "defaultFrameworkId", "defaultRoles", "defaultDeliverables", "thumbnail"] },
    { sheet: "FrameworkTemplates", columns: ["id", "name", "description", "defaultStages"] },
    { sheet: "StageTemplates", columns: ["id", "name", "description", "defaultTasks", "defaultRoles", "entryCriteria", "exitCriteria", "allowedTaskStatuses"] },
    { sheet: "DeliverableTemplates", columns: ["id", "title", "description", "defaultEpics"] },
    { sheet: "EpicTemplates", columns: ["id", "title", "description", "defaultStages"] },
    { sheet: "TaskTemplates", columns: ["id", "title", "description", "defaultPriority", "defaultEstimateHours", "requiredRole", "assignedRoleId", "scope", "assigneeRoleTypeId"] },
    { sheet: "RoleTemplates", columns: ["id", "name", "description", "defaultRoleType", "defaultPermissions"] },
    { sheet: "MilestoneTemplates", columns: ["id", "name", "description", "phase", "scopeType", "completionMode", "completionTargetPercent", "isBillingGate", "offsetDays", "stageTemplateId", "order", "defaultScopeRules"] },
    { sheet: "TemplateSnippets", columns: ["id", "name", "description", "type", "stageTemplateIds", "taskTemplateIds", "milestoneTemplateIds", "isDefault"] },
    { sheet: "StatusOptions", columns: ["id", "label", "color", "isDefault", "type", "order"] },
    { sheet: "RoleTypes", columns: ["id", "label", "description", "isDefault"] },
    { sheet: "MappingTemplates", columns: ["id", "name", "dataType"] },
    { sheet: "EpicTypes", columns: ["id", "name", "color", "icon", "isDefault", "order", "createdAt"] },
    { sheet: "DeliverableTypes", columns: ["id", "name", "color", "icon", "isDefault", "order", "createdAt"] },
    { sheet: "Users", columns: ["id", "name", "role", "email", "status", "avatar"] },
    { sheet: "ProjectRoles", columns: ["id", "name", "description", "roleType", "isRequired", "maxAssignees", "permissions"] },
    { sheet: "RoleAssignments", columns: ["id", "roleId", "userId", "isPrimary", "allocationPercent"] },
    { sheet: "UserRoleEligibility", columns: ["id", "userId", "roleTypeId"] },
    { sheet: "UserPreferences", columns: ["id", "userId", "workdayStartTime", "workdayEndTime", "defaultTargetDailyMinutes", "showOnlyActionable", "timezone"] },
    { sheet: "ProjectFavorites", columns: ["id", "userId", "projectId", "createdAt"] },
    { sheet: "WorkBlocks", columns: ["id", "userId", "date", "startTime", "endTime", "label", "taskIds", "totalPlannedMinutes", "status", "createdAt", "updatedAt"] },
    { sheet: "DayPlans", columns: ["id", "userId", "date", "targetWorkMinutes", "plannedMinutes", "unassignedTaskIds", "createdAt", "updatedAt"] }
  ],
  projects: [
    { sheet: "Projects", columns: ["id", "name", "description", "status", "startDate", "deadline", "progress", "frameworkId", "defaultMappingTemplateId", "permissions", "sprintDurationWeeks", "ownerId", "client", "riskLevel", "externalRefs"] },
    { sheet: "Deliverables", columns: ["id", "projectId", "title", "description", "status", "ownerId", "startDate", "dueDate", "progress", "externalRefs"] },
    { sheet: "Epics", columns: ["id", "deliverableId", "title", "description", "status", "ownerId", "startDate", "endDate", "progress", "stageIds", "externalRefs"] },
    { sheet: "ProjectStages", columns: ["id", "projectId", "name", "description", "order", "type", "status", "startDate", "endDate"] },
    { sheet: "Tasks", columns: ["id", "title", "description", "project", "projectId", "stageId", "epicId", "status", "assigneeId", "deadline", "priority", "milestoneId", "sprintId", "estimateHours", "effort", "tags", "blocked", "blockerReason", "updatedAt", "taskTypeId", "parentTaskId", "externalRefs"] },
    { sheet: "Milestones", columns: ["id", "projectId", "name", "description", "phase", "stageId", "targetDate", "status", "ownerId", "scopeType", "completionMode", "completionTargetPercent", "tags", "createdAt", "updatedAt", "progressTotalTasks", "progressCompletedTasks", "progressPercentComplete", "progressLastCalculatedAt", "progressPercent", "isBillingGate", "requiredCompletionRatio", "scopeRules", "createdBy", "updatedBy"] },
    { sheet: "MilestoneScopeRules", columns: ["id", "milestoneId", "rules", "lastEvaluatedAt"] },
    { sheet: "MilestoneTaskLinks", columns: ["id", "milestoneId", "taskId", "projectId", "source", "ruleId", "locked", "createdAt", "updatedAt"] },
    { sheet: "Sprints", columns: ["id", "projectId", "ownerUserId", "name", "goal", "startDate", "endDate", "status", "capacityHours", "notes", "autoStart", "closedAt", "createdAt", "updatedAt"] },
    { sheet: "SprintMembers", columns: ["id", "sprintId", "userId", "capacityHours", "capacityPoints"] },
    { sheet: "SprintScopeEvents", columns: ["id", "sprintId", "taskId", "userId", "eventType", "occurredAt", "note"] },
    { sheet: "SprintScopeTargets", columns: ["id", "sprintId", "targetType", "targetId", "autoSyncTasks", "createdAt"] },
    { sheet: "SprintPulseUpdates", columns: ["id", "sprintId", "userId", "date", "didText", "nextText", "blockersText", "referencedTaskIds", "createdAt", "updatedAt"] },
    { sheet: "TaskDependencies", columns: ["id", "taskId", "dependsOnTaskId", "dependencyType", "createdAt"] },
    { sheet: "ProjectTaskTypes", columns: ["id", "projectId", "taskTypeId", "name", "color", "icon", "isEnabled", "isDefault", "order", "createdAt"] },
    { sheet: "ProjectTaskStatuses", columns: ["id", "projectId", "label", "color", "isDefault", "order", "createdAt"] },
    { sheet: "ProjectSettings", columns: ["id", "projectId", "useCustomStatuses", "useCustomTaskTypes", "updatedAt"] },
    { sheet: "Activity", columns: ["id", "user", "action", "target", "time", "details", "avatar"] },
    { sheet: "Comments", columns: ["id", "taskId", "authorId", "authorName", "body", "createdAt"] },
    { sheet: "Attachments", columns: ["id", "taskId", "fileName", "url", "fileType", "size", "uploadedAt", "uploadedBy"] },
    { sheet: "History", columns: ["id", "taskId", "field", "oldValue", "newValue", "changedAt", "changedBy"] }
  ],
  templates: [
    { sheet: "ProjectTemplates", columns: ["id", "name", "description", "defaultFrameworkId", "defaultRoles", "defaultDeliverables", "thumbnail"] },
    { sheet: "FrameworkTemplates", columns: ["id", "name", "description", "defaultStages"] },
    { sheet: "StageTemplates", columns: ["id", "name", "description", "defaultTasks", "defaultRoles", "entryCriteria", "exitCriteria", "allowedTaskStatuses"] },
    { sheet: "DeliverableTemplates", columns: ["id", "title", "description", "defaultEpics"] },
    { sheet: "EpicTemplates", columns: ["id", "title", "description", "defaultStages"] },
    { sheet: "TaskTemplates", columns: ["id", "title", "description", "defaultPriority", "defaultEstimateHours", "requiredRole", "assignedRoleId", "scope", "assigneeRoleTypeId"] },
    { sheet: "RoleTemplates", columns: ["id", "name", "description", "defaultRoleType", "defaultPermissions"] },
    { sheet: "MilestoneTemplates", columns: ["id", "name", "description", "phase", "scopeType", "completionMode", "completionTargetPercent", "isBillingGate", "offsetDays", "stageTemplateId", "order", "defaultScopeRules"] },
    { sheet: "TemplateSnippets", columns: ["id", "name", "description", "type", "stageTemplateIds", "taskTemplateIds", "milestoneTemplateIds", "isDefault"] }
  ],
  defaults: [
    { sheet: "StatusOptions", columns: ["id", "label", "color", "isDefault", "type", "order"] },
    { sheet: "RoleTypes", columns: ["id", "label", "description", "isDefault"] },
    { sheet: "MappingTemplates", columns: ["id", "name", "dataType"] },
    { sheet: "GuidanceItems", columns: ["id", "title", "body", "priority", "stageId"] },
    { sheet: "SavedViews", columns: ["id", "name", "description", "stageIds", "viewType", "visibility", "isDefault", "config"] },
    { sheet: "TaskTypes", columns: ["id", "name", "color", "icon", "isDefault", "order", "createdAt"] },
    { sheet: "EpicTypes", columns: ["id", "name", "color", "icon", "isDefault", "order", "createdAt"] },
    { sheet: "DeliverableTypes", columns: ["id", "name", "color", "icon", "isDefault", "order", "createdAt"] }
  ],
  users: [
    { sheet: "Users", columns: ["id", "name", "role", "email", "status", "avatar"] },
    { sheet: "ProjectRoles", columns: ["id", "name", "description", "roleType", "isRequired", "maxAssignees", "permissions"] },
    { sheet: "RoleAssignments", columns: ["id", "roleId", "userId", "isPrimary", "allocationPercent"] },
    { sheet: "UserRoleEligibility", columns: ["id", "userId", "roleTypeId"] },
    { sheet: "UserPreferences", columns: ["id", "userId", "workdayStartTime", "workdayEndTime", "defaultTargetDailyMinutes", "showOnlyActionable", "timezone"] },
    { sheet: "ProjectFavorites", columns: ["id", "userId", "projectId", "createdAt"] },
    { sheet: "WorkBlocks", columns: ["id", "userId", "date", "startTime", "endTime", "label", "taskIds", "totalPlannedMinutes", "status", "createdAt", "updatedAt"] },
    { sheet: "DayPlans", columns: ["id", "userId", "date", "targetWorkMinutes", "plannedMinutes", "unassignedTaskIds", "createdAt", "updatedAt"] }
  ]
};

export const ENTITY_TO_COLLECTION: Record<string, string> = {
  Projects: "projects",
  Deliverables: "deliverables",
  Epics: "epics",
  ProjectStages: "projectStages",
  Tasks: "tasks",
  Milestones: "milestones",
  MilestoneScopeRules: "milestoneScopeRules",
  MilestoneTaskLinks: "milestoneTaskLinks",
  Sprints: "sprints",
  SprintMembers: "sprintMembers",
  SprintScopeEvents: "sprintScopeEvents",
  SprintScopeTargets: "sprintScopeTargets",
  SprintPulseUpdates: "sprintPulseUpdates",
  TaskDependencies: "taskDependencies",
  TaskTypes: "taskTypes",
  EpicTypes: "epicTypes",
  DeliverableTypes: "deliverableTypes",
  ProjectTaskTypes: "projectTaskTypes",
  ProjectTaskStatuses: "projectTaskStatuses",
  ProjectSettings: "projectSettings",
  Activity: "activity",
  Comments: "comments",
  Attachments: "attachments",
  History: "history",
  SavedViews: "savedViews",
  GuidanceItems: "guidanceItems",
  ProjectTemplates: "projectTemplates",
  FrameworkTemplates: "frameworkTemplates",
  StageTemplates: "stageTemplates",
  DeliverableTemplates: "deliverableTemplates",
  EpicTemplates: "epicTemplates",
  TaskTemplates: "taskTemplates",
  RoleTemplates: "roleTemplates",
  MilestoneTemplates: "milestoneTemplates",
  TemplateSnippets: "templateSnippets",
  StatusOptions: "statusOptions",
  RoleTypes: "roleTypes",
  MappingTemplates: "mappingTemplates",
  Users: "users",
  ProjectRoles: "projectRoles",
  RoleAssignments: "roleAssignments",
  UserRoleEligibility: "userRoleEligibility",
  UserPreferences: "userPreferences",
  ProjectFavorites: "projectFavorites",
  WorkBlocks: "workBlocks",
  DayPlans: "dayPlans"
};

export const DEFAULT_STATUS_VALUES: Record<string, string> = {
  projects: "Not Started",
  tasks: "Not Started",
  deliverables: "Not Started",
  epics: "Not Started",
  milestones: "Pending"
};

export const IMPORT_ORDER = [
  "Users",
  "RoleTypes",
  "StatusOptions",
  "TaskTypes",
  "EpicTypes",
  "DeliverableTypes",
  // Templates must be imported in dependency order:
  // TaskTemplates & RoleTemplates have no dependencies
  // StageTemplates references TaskTemplates and RoleTemplates
  // MilestoneTemplates may reference stages
  // FrameworkTemplates references StageTemplates
  "TaskTemplates",
  "RoleTemplates",
  "StageTemplates",
  "MilestoneTemplates",
  "DeliverableTemplates",
  "EpicTemplates",
  "ProjectTemplates",
  "FrameworkTemplates",
  "TemplateSnippets",
  "MappingTemplates",
  "GuidanceItems",
  "SavedViews",
  "UserRoleEligibility",
  "UserPreferences",
  "Projects",
  "ProjectFavorites",
  "ProjectRoles",
  "RoleAssignments",
  "ProjectSettings",
  "ProjectTaskTypes",
  "ProjectTaskStatuses",
  "ProjectStages",
  "Sprints",
  "SprintMembers",
  "SprintScopeTargets",
  "Deliverables",
  "Epics",
  "Milestones",
  "MilestoneScopeRules",
  "Tasks",
  "TaskDependencies",
  "MilestoneTaskLinks",
  "SprintScopeEvents",
  "SprintPulseUpdates",
  "Activity",
  "Comments",
  "Attachments",
  "History",
  "DayPlans",
  "WorkBlocks"
];
